name: Deploy images

on: [push, pull_request]

env:
  DOCKER_USERNAME: tobiaszimmer

jobs:
  deploy-images:
    name: Deploy images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup variables
        shell: bash
        run: |
          lower_case_image=$(echo $IMAGE_NAME | awk '{print tolower($0)}')
          echo "lower_case_image=$lower_case_image" >> $GITHUB_ENV
        env:
          IMAGE_NAME: ${{ env.DOCKER_USERNAME }}/${{ github.event.repository.name }}

      - name: Deploy to dockerhub
        if: ${{ github.event_name != 'pull_request' }}
        shell: bash
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
          
          cd src
          for directory in * ; do
            tag=$(basename "$directory")
            image="$lower_case_image:$tag-$(date +%k-%M-%F)"
            docker build --tag "$image" "$tag"
            docker push "$image"
          done

        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ env.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: ${{ env.lower_case_image }}
          provider: dockerhub
          short_description: "Docker images used to monitor our services"
          readme_file: "README.md"
